/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myapp_com_jnidemo_HelloCmake */

#ifndef _Included_myapp_com_jnidemo_HelloCmake
#define _Included_myapp_com_jnidemo_HelloCmake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myapp_com_jnidemo_HelloCmake
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_myapp_com_jnidemo_HelloCmake_getString
  (JNIEnv *, jobject);

/*
 * Class:     myapp_com_jnidemo_HelloCmake
 * Method:    getStringWithParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_myapp_com_jnidemo_HelloCmake_getStringWithParam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     myapp_com_jnidemo_HelloCmake
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_myapp_com_jnidemo_HelloCmake_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
